# Generated by Django 3.2.5 on 2021-07-10 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200, verbose_name='First Name')),
                ('lastname', models.CharField(max_length=200, verbose_name='Last Name')),
                ('admission_date', models.DateField(verbose_name='Admission Date')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Day_Of',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of', models.IntegerField(choices=[(2, 'Monday'), (3, 'Tuesday'), (4, 'Wednesday'), (5, 'Thursday'), (6, 'Friday'), (7, 'Saturday'), (1, 'Sunday')], verbose_name='Day Of')),
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='scheduleApp.doctor')),
            ],
            options={
                'verbose_name': 'Day Of',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=200, verbose_name='Country')),
                ('state', models.CharField(max_length=200, verbose_name='State')),
                ('city', models.CharField(max_length=200, verbose_name='City')),
                ('district', models.CharField(max_length=200, verbose_name='district')),
                ('street', models.CharField(max_length=200, verbose_name='Street')),
                ('number', models.IntegerField(verbose_name='Number')),
                ('place', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='scheduleApp.place')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduleApp.doctor')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduleApp.place')),
            ],
            options={
                'unique_together': {('date', 'doctor')},
            },
        ),
    ]
